// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqh4Si6e3Hu7DpMc6jprW0Mk_4mO5pCXM',
    appId: '1:168406256989:web:cf051dd53edb89ee3eecb4',
    messagingSenderId: '168406256989',
    projectId: 'alquilemos-en-la-playa',
    authDomain: 'alquilemos-en-la-playa.firebaseapp.com',
    storageBucket: 'alquilemos-en-la-playa.appspot.com',
    measurementId: 'G-MN8XSNJTWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9aAcVO2fGrD5Rnhhn_HA_TJxeEBgSGU',
    appId: '1:168406256989:android:30867cec63083a273eecb4',
    messagingSenderId: '168406256989',
    projectId: 'alquilemos-en-la-playa',
    storageBucket: 'alquilemos-en-la-playa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI5RwVQvwFdKurFOg4yO_5tuNXoflOiaA',
    appId: '1:168406256989:ios:0fda91addc9544a63eecb4',
    messagingSenderId: '168406256989',
    projectId: 'alquilemos-en-la-playa',
    storageBucket: 'alquilemos-en-la-playa.appspot.com',
    iosBundleId: 'com.example.alquilemosEnLaPlaya',
  );
}
